<?php

namespace Slicer\Exceptions;

class MappedExceptions {
    public static function all(){
        return array(
            10 => 'AuthMissingHeaderException',
            11 => 'AuthAPIKeyException',
            12 => 'AuthInvalidAPIKeyException',
            13 => 'AuthIncorrectPermissionException',
            14 => 'AuthInvalidRemoteException',
            16 => 'CustomKeyInvalidPermissionForFieldException',
            17 => 'CustomKeyInvalidOperationException',
            18 => 'CustomKeyNotPermittedException',
            19 => 'CustomKeyRouteNotPermittedException',
            # Request validations (20 - 29)
            21 => 'RequestMissingContentTypeException',
            22 => 'RequestIncorrectContentTypeValueException',
            23 => 'RequestRateLimitException',
            24 => 'RequestInvalidJsonException',
            # Account Errors (30 - 39)
            30 => 'AccountMissingPaymentMethodException',
            31 => 'AccountPaymentRequiredException',
            32 => 'AccountBannedException',
            33 => 'AccountDisabledException',
            # Field errors (40 - 59)
            40 => 'FieldMissingParamException',
            41 => 'FieldTypeException',
            42 => 'FieldIntegerValuesException',
            43 => 'FieldAlreadyExistsException',
            44 => 'FieldLimitException',
            45 => 'FieldTimeSeriesLimitException',
            46 => 'FieldTimeSeriesSystemLimitException',
            47 => 'FieldDecimalTypeException',
            48 => 'FieldStorageValueException',
            49 => 'FieldInvalidApiName',
            50 => 'FieldInvalidNameException',
            51 => 'FieldInvalidDescriptionException',
            53 => 'FieldInvalidCardinalityException',
            54 => 'FieldDecimalLimitException',
            55 => 'FieldRangeLimitException',
            # Index errors (60 - 79)
            60 => 'IndexEntityKeyTypeException',
            61 => 'IndexEntityValueTypeException',
            62 => 'IndexFieldNameTypeException',
            63 => 'IndexFieldTypeException',
            64 => 'IndexEntityNameTooBigException',
            65 => 'IndexFieldValueTooBigException',
            66 => 'IndexDateFormatException',
            67 => 'IndexFieldNotActiveException',
            68 => 'IndexIdLimitException',
            69 => 'IndexFieldLimitException',
            71 => 'IndexFieldStringEmptyValueException',
            72 => 'IndexFieldTimeseriesInvalidParameterException',
            73 => 'IndexFieldNumericInvalidValueException',
            74 => 'IndexFieldTimeseriesMissingValueException',
            75 => 'QueryTimeSeriesInvalidPrecisionSecondsException',
            76 => 'QueryTimeSeriesInvalidPrecisionMinutesException',
            77 => 'QueryTimeSeriesInvalidPrecisionHoursException',
            # Query errors (80 - 109)
            80 => 'QueryMissingQueryException',
            81 => 'QueryInvalidTypeException',
            82 => 'QueryMissingTypeParamException',
            83 => 'QueryInvalidOperatorException',
            84 => 'QueryIncorrectOperatorUsageException',
            85 => 'QueryFieldNotActiveException',
            86 => 'QueryMissingOperatorException',
            87 => 'QueryIncompleteException',
            88 => 'QueryEventCountQueryException',
            89 => 'QueryDateFormatException',
            90 => 'QueryIntegerException',
            91 => 'QueryFieldLimitException',
            92 => 'QueryLevelLimitException',
            93 => 'QueryBadAggsFormationException',
            94 => 'QueryInvalidAggFilterException',
            95 => 'QueryMetricsLevelException',
            96 => 'QueryTimeSeriesException',
            97 => 'QueryMetricsTypeException',
            98 => 'QueryContainsNumericException',
            99 => 'QueryExistsEntityLimitException',
            100 => 'QueryMultipleFiltersException',
            101 => 'QueryContainsValueTypeException',
            102 => 'QueryMissingNameParamException',
            103 => 'QuerySavedAlreadyExistsException',
            104 => 'QuerySavedNotExistsException',
            105 => 'QuerySavedInvalidTypeException',
            106 => 'MethodNotAllowedException',
            107 => 'QueryExistsMissingIdsException',
            108 => 'QueryInvalidFormatException',
            109 => 'QueryTopValuesParameterEmptyException',
            110 => 'QueryDataExtractionLimitValueException',
            111 => 'QueryDataExtractionLimitValueTooBigException',
            112 => 'QueryDataExtractionLimitAndPageTokenValueException',
            113 => 'QueryDataExtractionPageTokenValueException',
            114 => 'QueryDataExtractionFieldLimitException',
            115 => 'QueryExistsEntityEmptyException',
            116 => 'QuerySavedInvalidQueryValueException',
            117 => 'QuerySavedInvalidCachePeriodValueException',
            118 => 'QuerySavedInvalidNameException',
            119 => 'QueryCountInvalidParameterErrorException',
            120 => 'QueryAggregationInvalidParameterException',
            121 => 'QueryAggregationInvalidFilterQueryException',
            # Internal errors (110 - 120)
            130 => 'InternalServerException',
            131 => 'FieldCreateInternalException'
        );
    }
}
?>